[wokwi]
version = 1
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'

[[scenarios]]
name = "Menu Games Navigation"
actions = [
    [4000, "low", "13"],
    [4200, "high", "13"],
    [4500 "low", "4"],
    [4700, "high", "4"],
    [6000, "screenshot", "menu_games_navigation.png"]
]