name: PlatformIO & Wokwi CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Compilar Proyecto para ESP32
        run: pio run -e esp32dev

      - name: Instalar Wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh

      - name: Validar Diagrama de Wokwi
        run: wokwi-cli lint

      - name: Ejecutar simulación en Wokwi
        run: |
          wokwi-cli . --timeout 8000 --timeout-exit-code 0 \
            --screenshot-part oled1 \
            --screenshot-time 6000 \
            --screenshot-file menu_games_navigation.png
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}

      - name: Descargar Screenshot del Simulador
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-pantalla
          path: menu_games_navigation.png

      - name: Crear Release y subir Binario
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .pio/build/esp32dev/firmware.bin
            diagram.json
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
